name = "lustre"
version = "4.0.0-rc.2"
gleam = ">= 0.34.0"

description = "An Elm-inspired framework for building single page applications and server-rendered components in Gleam!"
repository = { type = "github", user = "lustre-labs", repo = "lustre" }
licences = ["MIT"]

links = [
  # { title = "Website", href = "https://lustre.build" },
  { title = "Examples", href = "https://github.com/lustre-labs/lustre/tree/main/examples" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = [
  "lustre/cli",
  "lustre/cli/*",
  "lustre/internals",
  "lustre/internals/*",
]

[documentation]
pages = [
  # { title = "CLI reference", path = "#", source = "" },
  # { title = " ", path = "#", source = "" },
  { title = "Quickstart guide", path = "guide/01-quickstart.html", source = "./pages/guide/01-quickstart.md" },
  # { title = "Managing state", path = "#", source = "" },
  # { title = "Side effects", path = "#", source = "" },
  # { title = "Server-side rendering", path = "#", source = "" },
  # { title = "Components", path = "#", source = "" },
  # { title = "Server components", path = "#", source = "" },
  # { title = " ", path = "#", source = "" },
  # { title = "Using with Wisp", path = "#", source = "" },
  # { title = "Using with Glen", path = "#", source = "" },
  # { title = "Using with Mist", path = "#", source = "" },
  # { title = " ", path = "#", source = "" },
  # { title = "For Elm developers", path = "#", source = "" },
  # { title = "For React developers", path = "#", source = "" },
  # { title = "For LiveView developers", path = "#", source = "" },
]

[dependencies]
argv = "~> 1.0"
filepath = "~> 0.1"
gleam_community_ansi = "~> 1.4"
gleam_erlang = "~> 0.24"
gleam_json = "~> 1.0"
gleam_otp = "~> 0.9"
gleam_stdlib = "~> 0.34 or ~> 1.0"
glint = "0.16.0"
justin = "~> 1.0"
shellout = "~> 1.6"
simplifile = "~> 1.4"
spinner = "~> 1.1"
tom = "~> 0.3"
gleam_package_interface = "~> 1.0"

[dev-dependencies]
birdie = "~> 1.0"
gleeunit = "~> 1.0"
